#!/bin/bash
# script 03 : copy setup files to user home
# run after exiting chroot
# usage: ./03-sethome

. common.sh

main() {
  local home_path

  home_path=$(find /mnt/home -mindepth 1 -maxdepth 1 -type d | fzf --tac --header "Select a home directory to copy files")
  [[ -z "${home_path}" ]] && {
    echo A home directory is mandatory to copy files
    exit
  }

  # copy pivate keys if rsa.iso.gpg present
  if [[ -f ~/rsa.iso.gpg && ! -f rsa.iso ]]; then
    echo -e "${TYS_Y}(TYS) Copy rsa keys to ${home_path}${TYS_NC}"
    gpg --output rsa.iso --decrypt ~/rsa.iso.gpg
    mkdir iso
    mount rsa.iso iso
    cp iso/id_* "${home_path}"
  fi

  echo -e "${TYS_Y}(TYS) Copy setup script to ${home_path}${TYS_NC}"
  cp 04-setup "${home_path}"

  answer=$(confirm "Reboot?" Y n)
  [[ "${answer}" == y ]] && {
    . unmount_partitions
    reboot
  }
}

main "${@}"
