#!/bin/bash
# script 04
# run first time after login
# usage: ./04-setup [-kc]

readonly nc=$'\e[0;m'
readonly y=$'\e[1;33m'

main() {
  local flags

  cd ~ || return

  mkdir ~/git || echo "'~/git' already exists"

  echo -e "${y}(TYS) Install ansible${nc}"
  sudo pacman --needed --noconfirm -S ansible

  # these flags are for tys private use
  # while getopts 'kc' flags; do
  #   case $flags in
  #     k)
  #       [[ -f ~/id_ed25519 && -f id_ed25519.pub ]] && {
  #         echo "${y}(TYS) Install ssh keys${nc}"
  #         mkdir ~/.ssh
  #         cp ~/id_* ~/.ssh
  #         chmod 700 ~/.ssh
  #         chmod 600 ~/.ssh/id_*
  #         sudo rm ~/id_*
  #       }
  #       exit
  #       ;;
  #     c)
  #       [[ -f ~/.ssh/id_ed25519 && -f ~/.ssh/id_ed25519.pub && ! -d ~/git/configs ]] && {
  #         echo "${y}(TYS) Clone private config repo${nc}"
  #         cd ~/git || return
  #         git clone git@github.com:doyonm/configs
  #       }
  #       exit
  #       ;;
  #     *)
  #       echo "A mind is like a parachute. It doesn't work if it is not open."
  #       exit
  #       ;;
  #   esac
  # done

  # [[ -z $flags && ! -d ~/git/setup ]] && {
  #   echo -e "${y}(TYS) Clone public setup repo${nc}"
  #   cd ~/git || return
  #   git clone https://codeberg.org/theyellowshark/setup.git
  #   echo -e "${y}(TYS) To install, run ~/git/setup/install/setup${nc}"
  # }
}

main "${@}"
