#!/bin/bash
# delete_partitions
# unmount and delete partitions according to install script partition schemes
# usage: ./delete_partitions

. common.sh
. defaults.sh

rm_part() {
  echo -e "${TYS_Y}(TYS) Delete partition ${1}${TYS_NC}"
  parted -s "${2}" rm "${1}"
}

main() {
  local device proceed pnbr

  device=$(select_block_device) || exit $?

  pnbr=$(grep -c "${device}[0-9]" /proc/partitions)
  [[ "${pnbr}" == 0 ]] && exit

  device=/dev/"${device}"

  lsblk
  proceed=$(confirm "(TYS) DELETE partitions on ${device}?" y N) || exit $?
  [[ "${proceed}" != "y" ]] && exit

  . unmount_partitions

  [[ "${pnbr}" == 3 ]] && {
    rm_part 3 "${device}"
  }
  rm_part 2 "${device}"
  rm_part 1 "${device}"
}

main "${@}"
