#!/bin/bash
# delete_partitions
# unmount and delete partitions
# usage: ./delete_partitions

. common.sh
. defaults.sh

unmount_all() {
  mountpoint -q /mnt && {
    echo -e "${TYS_Y}(TYS) Unmounting${TYS_NC}"
    umount -R /mnt
  }
}

crypt_close() {
  [[ -b ${1} ]] && {
    echo -e "${TYS_Y}(TYS) Close luks${TYS_NC}"
    cryptsetup close "${1}"
  }
}

main() {
  unmount_all
  crypt_close "${TYS_DEFAULT_LUKSROOT}"
}

main "${@}"
